# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'rePear' do
pod 'YouTubePlayer'
pod 'Chatto', '= 1.0.0'
pod 'ChattoAdditions', '= 1.0.0' # if you want to use the cells or the input component

end

